version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: ihome24-postgres
    environment:
      POSTGRES_DB: ihome24
      POSTGRES_USER: iHome24db
      POSTGRES_PASSWORD: iHome242025db
    ports:
      - "5434:5432"
